parameters:
  - name: envs
    type: object

stages:
- ${{ each environment in parameters.envs }}:
  - stage: ${{ environment }} 
    variables:
      - template: "${{ environment }}.yml"
    jobs:
    - job: testing
      steps:
      - bash: echo $(myVariable1)